const VAULT_FETCH_APYS_BEGIN = "VAULT_FETCH_APYS_BEGIN";
const VAULT_FETCH_APYS_SUCCESS = "VAULT_FETCH_APYS_SUCCESS";
const VAULT_FETCH_APYS_FAILURE = "VAULT_FETCH_APYS_FAILURE";
const VAULT_UPDATE_POOL_BEGIN = "VAULT_UPDATE_POOL_BEGIN";
const VAULT_UPDATE_POOL_SUCCESS = "VAULT_UPDATE_POOL_SUCCESS";
const VAULT_UPDATE_POOL_FAILURE = "VAULT_UPDATE_POOL_FAILURE";

export {
  VAULT_FETCH_APYS_BEGIN,
  VAULT_FETCH_APYS_SUCCESS,
  VAULT_FETCH_APYS_FAILURE,
  VAULT_UPDATE_POOL_BEGIN,
  VAULT_UPDATE_POOL_SUCCESS,
  VAULT_UPDATE_POOL_FAILURE,
};
