const VAULT_FETCH_APYS_BEGIN = "VAULT_FETCH_APYS_BEGIN";
const VAULT_FETCH_APYS_SUCCESS = "VAULT_FETCH_APYS_SUCCESS";
const VAULT_FETCH_APYS_FAILURE = "VAULT_FETCH_APYS_FAILURE";

export {
  VAULT_FETCH_APYS_BEGIN,
  VAULT_FETCH_APYS_SUCCESS,
  VAULT_FETCH_APYS_FAILURE,
};
